name: main-build

on:
  push:
    tags:
      - 'v*'
      - 'dev-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Inject dynamic build parameters into json files
        shell: pwsh
        run: '_tasks/Initialize-BuildContext.ps1'

      - name: Compile Azure Devops Extension
        run: tfx extension create --manifest-globs bc-tools-extension/vss-extension.json

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: bc-extension-dev
          path: '*.vsix'